#!/usr/bin/env bash
# Desktop themes (Settings → Personalization → Themes). A theme is a JSON (temas/nothing.json
# as an example): «colors» with Theme.qml's tokens and «terminal» with the terminal's 16 colors.
#   aplicar <tema.json>   applies it to the whole desktop: copies it to ~/.local/share/quickshell/tema/
#                         actual.json (Theme.qml reads it live) and generates each program's files:
#                           Alacritty  ~/.local/share/quickshell/tema/alacritty.toml (imported)
#                           walker     ~/.config/walker/themes/nothing/tema.css (imported by style.css)
#                           GTK 3 & 4  ~/.config/gtk-{3,4}.0/tema.css (imported by gtk.css; also
#                                      next to the real file in the repo, the symlink's target)
#                           Hyprland   ~/.config/hypr/conf/tema.lua (borders; pcall(require) in hyprland.lua)
#                         The ones inside the repo are in .gitignore. Then Hyprland and walker reload.
#   lista                 tema|file|{json}  of the bundled (temas/) and installed ones
#                         (~/.local/share/quickshell/temas/)
#   guardar               saves the JSON on stdin as an installed theme (its «id» is the name)
#   quitar <id>           deletes an installed theme (not bundled ones)
#   catalogo [--actualizar]
#                         base16 schemes from tinted-theming (downloaded once to ~/.cache):
#                         esquema|id|name|author|variant|base00|…|base0F  (hex without «#»)
LC_ALL=C
export LC_ALL
AQUI=$(dirname "$(readlink -f "$0")")
INCLUIDOS="$AQUI/../temas"
INSTALADOS="$HOME/.local/share/quickshell/temas"
DATOS="$HOME/.local/share/quickshell/tema"
CACHE="$HOME/.cache/quickshell/base16"

# Hyprland's rgba(rrggbbaa) from #rrggbb
hypr() { printf 'rgba(%s%s)' "${1#\#}" "${2:-ff}"; }

aplicar() {
    local f=$1
    [[ -f $f ]] || { echo "$f does not exist" >&2; exit 1; }
    jq -e '.colors.bg and .terminal.normal' "$f" >/dev/null 2>&1 || { echo "$f is not a valid theme" >&2; exit 1; }
    mkdir -p "$DATOS"
    cp -f "$f" "$DATOS/actual.json.tmp" && mv -f "$DATOS/actual.json.tmp" "$DATOS/actual.json"
    c() { jq -r ".colors.$1" "$f"; }
    t() { jq -r ".terminal.$1" "$f"; }

    # --- Alacritty ---
    local n=(black red green yellow blue magenta cyan white) i
    {
        echo "# Generated by quickshell/scripts/tema.sh ($(jq -r .name "$f")). Do not edit: change the theme in Settings."
        echo "[colors.primary]"
        echo "background = \"$(t background)\""; echo "foreground = \"$(t foreground)\""
        echo "[colors.cursor]"
        echo "text = \"$(t cursorText)\""; echo "cursor = \"$(t cursor)\""
        echo "[colors.vi_mode_cursor]"
        echo "text = \"$(t cursorText)\""; echo "cursor = \"$(t viCursor)\""
        echo "[colors.selection]"
        echo "text = \"$(t selectionText)\""; echo "background = \"$(t selection)\""
        echo "[colors.search]"
        echo "matches = { foreground = \"$(t selectionText)\", background = \"$(t searchMatch)\" }"
        echo "focused_match = { foreground = \"$(t cursorText)\", background = \"$(t cursor)\" }"
        echo "[colors.hints]"
        echo "start = { foreground = \"$(t cursorText)\", background = \"$(t cursor)\" }"
        echo "end = { foreground = \"$(t selectionText)\", background = \"$(t selection)\" }"
        echo "[colors.footer_bar]"
        echo "foreground = \"$(t selectionText)\""; echo "background = \"$(t selection)\""
        echo "[colors.normal]"
        for i in 0 1 2 3 4 5 6 7; do echo "${n[i]} = \"$(jq -r ".terminal.normal[$i]" "$f")\""; done
        echo "[colors.bright]"
        for i in 0 1 2 3 4 5 6 7; do echo "${n[i]} = \"$(jq -r ".terminal.bright[$i]" "$f")\""; done
    } >"$DATOS/alacritty.toml"

    # --- walker ---
    local w="$HOME/.config/walker/themes/nothing"
    if [[ -d $w ]]; then
        {
            echo "/* Generated by quickshell/scripts/tema.sh: desktop theme colors (loaded after colors.css) */"
            local k
            for k in bg bg_alt:bgAlt surface control control_hi:controlHi border fg fg_soft:fgSoft dim \
                     accent accent_text:accentText red sel sel_hi:selHi sel_soft:selSoft sel_text:selText; do
                echo "@define-color ${k%%:*} $(c "${k#*:}");"
            done
        } >"$w/tema.css"
    fi

    # --- GTK 3 and 4 (libadwaita / adw-gtk3) ---
    # gtk.css (a symlink into the repo) imports «tema.css»: it is written next to the symlink and next to the real file,
    # in case GTK resolves the relative path from one or the other
    local g d sombra="rgba(0, 0, 0, 0.36)"
    for g in "$HOME/.config/gtk-3.0" "$HOME/.config/gtk-4.0"; do
        mkdir -p "$g"
        {
            echo "/* Generated by quickshell/scripts/tema.sh ($(jq -r .name "$f")): imported by gtk.css */"
            echo "@define-color accent_color $(c accent);"; echo "@define-color accent_bg_color $(c accent);"
            echo "@define-color accent_fg_color $(c accentText);"
            for k in destructive error; do
                echo "@define-color ${k}_color $(c red);"; echo "@define-color ${k}_bg_color $(c red);"
                echo "@define-color ${k}_fg_color $(c selText);"
            done
            for k in success warning; do
                echo "@define-color ${k}_color $(c fgSoft);"; echo "@define-color ${k}_bg_color $(c controlHi);"
                echo "@define-color ${k}_fg_color $(c fg);"
            done
            echo "@define-color window_bg_color $(c bg);"; echo "@define-color window_fg_color $(c fg);"
            echo "@define-color view_bg_color $(c bgAlt);"; echo "@define-color view_fg_color $(c fg);"
            echo "@define-color headerbar_bg_color $(c bg);"; echo "@define-color headerbar_fg_color $(c fg);"
            echo "@define-color headerbar_border_color $(c border);"; echo "@define-color headerbar_backdrop_color $(c bg);"
            echo "@define-color headerbar_shade_color $sombra;"
            for k in sidebar secondary_sidebar; do
                echo "@define-color ${k}_bg_color $(c bgAlt);"; echo "@define-color ${k}_fg_color $(c fg);"
            done
            echo "@define-color sidebar_backdrop_color $(c bgAlt);"; echo "@define-color sidebar_shade_color $sombra;"
            echo "@define-color card_bg_color $(c surface);"; echo "@define-color card_fg_color $(c fg);"
            echo "@define-color card_shade_color $sombra;"
            echo "@define-color thumbnail_bg_color $(c surface);"; echo "@define-color thumbnail_fg_color $(c fg);"
            echo "@define-color dialog_bg_color $(c bgAlt);"; echo "@define-color dialog_fg_color $(c fg);"
            echo "@define-color popover_bg_color $(c bgAlt);"; echo "@define-color popover_fg_color $(c fg);"
            echo "@define-color popover_shade_color $sombra;"; echo "@define-color shade_color $sombra;"
            echo "@define-color scrollbar_outline_color $(c border);"
        } >"$g/tema.css"
        d=$(dirname "$(readlink -f "$g/gtk.css" 2>/dev/null)")
        [[ -n $d && $d != "$g" && -d $d ]] && cp -f "$g/tema.css" "$d/tema.css"
    done
    command -v gsettings >/dev/null && gsettings set org.gnome.desktop.interface color-scheme \
        "$([[ $(jq -r '.variant // "dark"' "$f") == light ]] && echo prefer-light || echo prefer-dark)" 2>/dev/null

    # --- Hyprland (bordes) ---
    if [[ -d $HOME/.config/hypr/conf ]]; then
        cat >"$HOME/.config/hypr/conf/tema.lua" <<LUA
-- Generated by quickshell/scripts/tema.sh ($(jq -r .name "$f")): window borders. Do not edit.
hl.config({
    general = {
        col = {
            active_border   = "$(hypr "$(c accent)" ee)",
            inactive_border = "$(hypr "$(c border)" ff)",
        },
    },
})
LUA
        command -v hyprctl >/dev/null && hyprctl reload >/dev/null 2>&1
    fi
    # walker reads its CSS on startup
    systemctl --user is-active --quiet walker.service 2>/dev/null && systemctl --user restart walker.service
    echo "aplicado|$(jq -r .id "$f")"
}

catalogo() {
    if [[ ! -d $CACHE || $1 == --actualizar ]]; then
        local tmp; tmp=$(mktemp -d)
        if curl -fsSL -m 60 https://codeload.github.com/tinted-theming/schemes/tar.gz/HEAD | tar xz -C "$tmp" 2>/dev/null ||
           git clone -q --depth 1 https://github.com/tinted-theming/schemes "$tmp/schemes" 2>/dev/null; then
            rm -rf "$CACHE"; mkdir -p "$CACHE"
            cp "$tmp"/*/base16/*.yaml "$CACHE/" 2>/dev/null
        fi
        rm -rf "$tmp"
    fi
    [[ -d $CACHE ]] || { echo "error|Could not download the catalog" ; exit 1; }
    local y
    for y in "$CACHE"/*.yaml; do
        awk -v id="$(basename "$y" .yaml)" '
            function v(s) { sub(/^[^:]*:[ \t]*/, "", s); sub(/[ \t]+#.*$/, "", s); gsub(/"/, "", s); gsub(/\|/, "/", s); return s }
            /^name:/ { n = v($0) } /^author:/ { a = v($0) } /^variant:/ { va = v($0) }
            /^[ \t]*base0[0-9A-Fa-f]:/ { k = $1; sub(/:$/, "", k); sub(/^[ \t]*/, "", k); c = v($0); sub(/^#/, "", c); p[toupper(substr(k, 5, 2))] = tolower(c) }
            END {
                if (n == "" || length(p) < 16) exit
                printf "esquema|%s|%s|%s|%s", id, n, a, (va != "" ? va : "dark")
                split("00 01 02 03 04 05 06 07 08 09 0A 0B 0C 0D 0E 0F", ks, " ")
                for (i = 1; i <= 16; i++) printf "|%s", p[ks[i]]
                printf "\n" }' "$y"
    done
}

case $1 in
aplicar) aplicar "$2" ;;
lista)
    for f in "$INCLUIDOS"/*.json "$INSTALADOS"/*.json; do
        [[ -f $f ]] && echo "tema|$f|$(jq -c . "$f" 2>/dev/null)"
    done
    echo "actual|$(jq -r .id "$DATOS/actual.json" 2>/dev/null || echo nothing)"
    ;;
guardar)
    mkdir -p "$INSTALADOS"
    j=$(cat); id=$(jq -r .id <<<"$j")
    [[ $id =~ ^[A-Za-z0-9._-]+$ ]] || { echo "invalid id" >&2; exit 1; }
    jq . <<<"$j" >"$INSTALADOS/$id.json" && echo "$INSTALADOS/$id.json"
    ;;
quitar) [[ $2 =~ ^[A-Za-z0-9._-]+$ ]] && rm -f "$INSTALADOS/$2.json" ;;
catalogo) catalogo "$2" ;;
*) echo "uso: $0 aplicar <tema.json> | lista | guardar < json | quitar <id> | catalogo [--actualizar]" >&2; exit 1 ;;
esac
