#!/usr/bin/env bash
# Desktop themes (Settings → Personalization → Themes). A theme is a JSON (themes/nothing.json
# as an example): «colors» with Theme.qml's tokens and «terminal» with the terminal's 16 colors.
#   apply <theme.json>   applies it to the whole desktop: copies it to ~/.local/share/quickshell/theme/
#                        current.json (Theme.qml reads it live) and generates each program's files:
#                          Alacritty  ~/.local/share/quickshell/theme/alacritty.toml (imported)
#                          walker     ~/.config/walker/themes/nothing/theme.css (imported by style.css)
#                          GTK 3 & 4  ~/.config/gtk-{3,4}.0/theme.css (imported by gtk.css; also
#                                     next to the real file in the repo, the symlink's target)
#                          Hyprland   ~/.config/hypr/conf/theme.lua (borders; pcall(require) in hyprland.lua)
#                        The ones inside the repo are in .gitignore. Then Hyprland and walker reload.
#   list                 theme|file|{json}  of the bundled (themes/) and installed ones
#                        (~/.local/share/quickshell/themes/), then current|<id>
#   save                 saves the JSON on stdin as an installed theme (its «id» is the name)
#   remove <id>          deletes an installed theme (not bundled ones)
#   catalog [--refresh]  base16 schemes from tinted-theming (downloaded once to ~/.cache):
#                        scheme|id|name|author|variant|base00|…|base0F  (hex without «#»)
LC_ALL=C
export LC_ALL
HERE=$(dirname "$(readlink -f "$0")")
BUNDLED="$HERE/../themes"
INSTALLED="$HOME/.local/share/quickshell/themes"
DATA="$HOME/.local/share/quickshell/theme"
CACHE="$HOME/.cache/quickshell/base16"

# Hyprland's rgba(rrggbbaa) from #rrggbb
hypr() { printf 'rgba(%s%s)' "${1#\#}" "${2:-ff}"; }

apply() {
    local f=$1
    [[ -f $f ]] || { echo "$f does not exist" >&2; exit 1; }
    jq -e '.colors.bg and .terminal.normal' "$f" >/dev/null 2>&1 || { echo "$f is not a valid theme" >&2; exit 1; }
    mkdir -p "$DATA"
    cp -f "$f" "$DATA/current.json.tmp" && mv -f "$DATA/current.json.tmp" "$DATA/current.json"
    c() { jq -r ".colors.$1" "$f"; }
    term() { jq -r ".terminal.$1" "$f"; }

    # --- Alacritty ---
    local n=(black red green yellow blue magenta cyan white) i
    {
        echo "# Generated by quickshell/scripts/theme.sh ($(jq -r .name "$f")). Do not edit: change the theme in Settings."
        echo "[colors.primary]"
        echo "background = \"$(term background)\""; echo "foreground = \"$(term foreground)\""
        echo "[colors.cursor]"
        echo "text = \"$(term cursorText)\""; echo "cursor = \"$(term cursor)\""
        echo "[colors.vi_mode_cursor]"
        echo "text = \"$(term cursorText)\""; echo "cursor = \"$(term viCursor)\""
        echo "[colors.selection]"
        echo "text = \"$(term selectionText)\""; echo "background = \"$(term selection)\""
        echo "[colors.search]"
        echo "matches = { foreground = \"$(term selectionText)\", background = \"$(term searchMatch)\" }"
        echo "focused_match = { foreground = \"$(term cursorText)\", background = \"$(term cursor)\" }"
        echo "[colors.hints]"
        echo "start = { foreground = \"$(term cursorText)\", background = \"$(term cursor)\" }"
        echo "end = { foreground = \"$(term selectionText)\", background = \"$(term selection)\" }"
        echo "[colors.footer_bar]"
        echo "foreground = \"$(term selectionText)\""; echo "background = \"$(term selection)\""
        echo "[colors.normal]"
        for i in 0 1 2 3 4 5 6 7; do echo "${n[i]} = \"$(jq -r ".terminal.normal[$i]" "$f")\""; done
        echo "[colors.bright]"
        for i in 0 1 2 3 4 5 6 7; do echo "${n[i]} = \"$(jq -r ".terminal.bright[$i]" "$f")\""; done
    } >"$DATA/alacritty.toml"

    # --- walker ---
    local w="$HOME/.config/walker/themes/nothing"
    if [[ -d $w ]]; then
        {
            echo "/* Generated by quickshell/scripts/theme.sh: desktop theme colors (loaded after colors.css) */"
            local k
            for k in bg bg_alt:bgAlt surface control control_hi:controlHi border fg fg_soft:fgSoft dim \
                     accent accent_text:accentText red sel sel_hi:selHi sel_soft:selSoft sel_text:selText; do
                echo "@define-color ${k%%:*} $(c "${k#*:}");"
            done
        } >"$w/theme.css"
        rm -f "$w/tema.css"   # its name before the move to English
    fi

    # --- GTK 3 and 4 (libadwaita / adw-gtk3) ---
    # gtk.css (a symlink into the repo) imports «theme.css»: it is written next to the symlink and next
    # to the real file, in case GTK resolves the relative path from one or the other
    local g d shade="rgba(0, 0, 0, 0.36)"
    for g in "$HOME/.config/gtk-3.0" "$HOME/.config/gtk-4.0"; do
        mkdir -p "$g"
        {
            echo "/* Generated by quickshell/scripts/theme.sh ($(jq -r .name "$f")): imported by gtk.css */"
            echo "@define-color accent_color $(c accent);"; echo "@define-color accent_bg_color $(c accent);"
            echo "@define-color accent_fg_color $(c accentText);"
            for k in destructive error; do
                echo "@define-color ${k}_color $(c red);"; echo "@define-color ${k}_bg_color $(c red);"
                echo "@define-color ${k}_fg_color $(c selText);"
            done
            for k in success warning; do
                echo "@define-color ${k}_color $(c fgSoft);"; echo "@define-color ${k}_bg_color $(c controlHi);"
                echo "@define-color ${k}_fg_color $(c fg);"
            done
            echo "@define-color window_bg_color $(c bg);"; echo "@define-color window_fg_color $(c fg);"
            echo "@define-color view_bg_color $(c bgAlt);"; echo "@define-color view_fg_color $(c fg);"
            echo "@define-color headerbar_bg_color $(c bg);"; echo "@define-color headerbar_fg_color $(c fg);"
            echo "@define-color headerbar_border_color $(c border);"; echo "@define-color headerbar_backdrop_color $(c bg);"
            echo "@define-color headerbar_shade_color $shade;"
            for k in sidebar secondary_sidebar; do
                echo "@define-color ${k}_bg_color $(c bgAlt);"; echo "@define-color ${k}_fg_color $(c fg);"
            done
            echo "@define-color sidebar_backdrop_color $(c bgAlt);"; echo "@define-color sidebar_shade_color $shade;"
            echo "@define-color card_bg_color $(c surface);"; echo "@define-color card_fg_color $(c fg);"
            echo "@define-color card_shade_color $shade;"
            echo "@define-color thumbnail_bg_color $(c surface);"; echo "@define-color thumbnail_fg_color $(c fg);"
            echo "@define-color dialog_bg_color $(c bgAlt);"; echo "@define-color dialog_fg_color $(c fg);"
            echo "@define-color popover_bg_color $(c bgAlt);"; echo "@define-color popover_fg_color $(c fg);"
            echo "@define-color popover_shade_color $shade;"; echo "@define-color shade_color $shade;"
            echo "@define-color scrollbar_outline_color $(c border);"
        } >"$g/theme.css"
        rm -f "$g/tema.css"
        d=$(dirname "$(readlink -f "$g/gtk.css" 2>/dev/null)")
        [[ -n $d && $d != "$g" && -d $d ]] && { cp -f "$g/theme.css" "$d/theme.css"; rm -f "$d/tema.css"; }
    done
    command -v gsettings >/dev/null && gsettings set org.gnome.desktop.interface color-scheme \
        "$([[ $(jq -r '.variant // "dark"' "$f") == light ]] && echo prefer-light || echo prefer-dark)" 2>/dev/null

    # --- Hyprland (borders) ---
    if [[ -d $HOME/.config/hypr/conf ]]; then
        cat >"$HOME/.config/hypr/conf/theme.lua" <<LUA
-- Generated by quickshell/scripts/theme.sh ($(jq -r .name "$f")): window borders. Do not edit.
hl.config({
    general = {
        col = {
            active_border   = "$(hypr "$(c accent)" ee)",
            inactive_border = "$(hypr "$(c border)" ff)",
        },
    },
})
LUA
        rm -f "$HOME/.config/hypr/conf/tema.lua"
        command -v hyprctl >/dev/null && hyprctl reload >/dev/null 2>&1
    fi
    # walker reads its CSS on startup
    systemctl --user is-active --quiet walker.service 2>/dev/null && systemctl --user restart walker.service
    echo "applied|$(jq -r .id "$f")"
}

catalog() {
    if [[ ! -d $CACHE || $1 == --refresh ]]; then
        local tmp; tmp=$(mktemp -d)
        if curl -fsSL -m 60 https://codeload.github.com/tinted-theming/schemes/tar.gz/HEAD | tar xz -C "$tmp" 2>/dev/null ||
           git clone -q --depth 1 https://github.com/tinted-theming/schemes "$tmp/schemes" 2>/dev/null; then
            rm -rf "$CACHE"; mkdir -p "$CACHE"
            cp "$tmp"/*/base16/*.yaml "$CACHE/" 2>/dev/null
        fi
        rm -rf "$tmp"
    fi
    [[ -d $CACHE ]] || { echo "error|Could not download the catalog" ; exit 1; }
    local y
    for y in "$CACHE"/*.yaml; do
        awk -v id="$(basename "$y" .yaml)" '
            function v(s) { sub(/^[^:]*:[ \t]*/, "", s); sub(/[ \t]+#.*$/, "", s); gsub(/"/, "", s); gsub(/\|/, "/", s); return s }
            /^name:/ { n = v($0) } /^author:/ { a = v($0) } /^variant:/ { va = v($0) }
            /^[ \t]*base0[0-9A-Fa-f]:/ { k = $1; sub(/:$/, "", k); sub(/^[ \t]*/, "", k); c = v($0); sub(/^#/, "", c); p[toupper(substr(k, 5, 2))] = tolower(c) }
            END {
                if (n == "" || length(p) < 16) exit
                printf "scheme|%s|%s|%s|%s", id, n, a, (va != "" ? va : "dark")
                split("00 01 02 03 04 05 06 07 08 09 0A 0B 0C 0D 0E 0F", ks, " ")
                for (i = 1; i <= 16; i++) printf "|%s", p[ks[i]]
                printf "\n" }' "$y"
    done
}

case $1 in
apply) apply "$2" ;;
list)
    for f in "$BUNDLED"/*.json "$INSTALLED"/*.json; do
        [[ -f $f ]] && echo "theme|$f|$(jq -c . "$f" 2>/dev/null)"
    done
    echo "current|$(jq -r .id "$DATA/current.json" 2>/dev/null || echo nothing)"
    ;;
save)
    mkdir -p "$INSTALLED"
    j=$(cat); id=$(jq -r .id <<<"$j")
    [[ $id =~ ^[A-Za-z0-9._-]+$ ]] || { echo "invalid id" >&2; exit 1; }
    jq . <<<"$j" >"$INSTALLED/$id.json" && echo "$INSTALLED/$id.json"
    ;;
remove) [[ $2 =~ ^[A-Za-z0-9._-]+$ ]] && rm -f "$INSTALLED/$2.json" ;;
catalog) catalog "$2" ;;
*) echo "usage: $0 apply <theme.json> | list | save < json | remove <id> | catalog [--refresh]" >&2; exit 1 ;;
esac
