-- Hyprland configuration, split into modules under conf/
-- Official guide: https://wiki.hypr.land/Configuring/Core/#using-multiple-configuration-files
-- Each require() runs in its own scope: if one module fails,
-- the others still load. Everything that is loaded is in this list.

require("conf.monitors")
require("conf.env")
require("conf.autostart")
require("conf.permissions")
require("conf.look-and-feel")
pcall(require, "conf.theme")        -- desktop theme borders (generated by quickshell/scripts/theme.sh; if missing, look-and-feel's)
require("conf.layouts")
require("conf.misc")
require("conf.input")
pcall(require, "conf.shell-settings")  -- generated by the shell (Settings; not in git): gaps, rounding, keyboard and mouse. If it does not exist yet, qs creates it on startup
require("conf.xwayland")
require("conf.keybinds")
require("conf.rules")
