-- Input: gestures, specific devices and per-app rules
-- See https://wiki.hypr.land/Configuring/Basics/Variables/#input
--
-- The general input options (keyboard layout and options, repeat, Num Lock,
-- sensitivity, acceleration, focus, left-handed and all of the touchpad) are in conf/shell-settings.lua,
-- generated by Settings → Keyboard and mouse. Do not put them here: that page overrides this file.

hl.gesture({
    fingers = 3,
    direction = "horizontal",
    action = "workspace"
})

-- See https://wiki.hypr.land/Configuring/Advanced-and-Cool/Devices/ for more
hl.device({
  name = "logitech-m705",
  -- sensitivity: the general one from Settings → Keyboard and mouse (conf/shell-settings.lua)
  accel_profile = "flat",
  scroll_factor = 0.6,
})

-- App-specific touchpad scroll speeds.
hl.window_rule({
    name  = "cs2-scroll",
    match = { class = "cs2" },
    scroll_mouse = 0.6,
})
