#!/usr/bin/env python3
"""Keeps a machine's own Hyprland monitors and autostart apps when the dotfiles are installed.

    hypr-import.py [--from OLD_HYPR_DIR] CONF_DIR

CONF_DIR is the repo's home/.config/hypr/conf. Two files there are yours, not in git, and are only
written if they do not exist yet:

  monitors.lua          the hl.monitor rules, taken from (in this order) the old config's
                        monitor= / monitorv2 / hl.monitor rules, the running Hyprland session
                        (hyprctl monitors all -j) or nothing; a fallback rule for any other
                        monitor (preferred mode, automatic position and scale) is always added.
  autostart-local.lua   the old config's exec-once / exec / hl.exec_cmd commands, as a list that
                        conf/autostart.lua runs on start. What this desktop already starts or
                        replaces (bar, notifications, wallpaper, idle, lock…) is written commented out.

The old config can be hyprlang (hyprland.conf, following source=) or Lua (hyprland.lua and the
files it requires). Output, one line per file, for install.sh to report:
    monitors|<source: config|session|fallback|kept>|<rules>
    autostart|<written|none|kept|skipped>|<commands>|<commented out>
"""
import glob
import json
import os
import re
import subprocess
import sys

HOME = os.path.expanduser("~")

MONITORS_HEADER = (
    "-- Monitors — https://wiki.hypr.land/Configuring/Basics/Monitors/\n"
    "-- Rewritten by Settings → Displays on apply (only the hl.monitor of connected monitors;\n"
    "-- the others stay as they are). It can also be edited by hand: the form reads Hyprland's\n"
    "-- real values. Anything that is not hl.monitor is lost when applying from Settings.\n"
    "-- Yours, not in git: generated by install.sh (links module) from this machine's config.\n\n"
)
FALLBACK = 'hl.monitor({ output = "", mode = "preferred", position = "auto", scale = "auto" })'

AUTOSTART_HEADER = (
    "-- Your own autostart apps (not in git), run by conf/autostart.lua when Hyprland starts.\n"
    "-- Imported by install.sh from your previous Hyprland config. One command per line, as a\n"
    "-- shell command (hl.exec_cmd runs it with sh -c). Lines starting with -- are ignored.\n"
)
# Already started (or replaced) by this desktop: imported commented out, so two bars, two
# notification daemons or two lock screens do not fight
PROVIDED = [
    (r"\b(waybar|hyprpanel|ags|eww|nwg-panel|ironbar|polybar)\b", "the bar is the Quickshell shell"),
    (r"\b(dunst|mako|swaync|swaync-client|fnott|notify-osd)\b", "notifications come from the shell"),
    (r"\b(hyprpaper|swww|swww-daemon|swaybg|mpvpaper|wpaperd|waypaper)\b", "the wallpaper is drawn by the shell"),
    (r"\b(hypridle|swayidle|xidlehook)\b", "hypridle is already started (settings in Settings → Lock)"),
    (r"\b(hyprlock|swaylock|gtklock)\b", "the lock screen is the shell's (lock-screen)"),
    (r"\b(qs|quickshell|walker|elephant|lock-screen)\b", "already started by conf/autostart.lua"),
    (r"(import-environment|dbus-update-activation-environment)", "already done by conf/autostart.lua"),
    (r"\b(wofi|rofi|fuzzel|tofi|anyrun)\b", "the launcher is walker"),
    (r"\b(cliphist|wl-paste\s+--watch|clipse)\b", "the clipboard history is walker's"),
    (r"\b(hyprsunset|gammastep|wlsunset)\b", "check it does not clash with Settings → Displays"),
]


# ---------------------------------------------------------------- hyprlang (hyprland.conf)

def hyprlang_lines(path, old_dir, seen):
    """Lines of a hyprlang file, with source= files inlined (recursively)."""
    path = os.path.realpath(path)
    if path in seen or not os.path.isfile(path):
        return []
    seen.add(path)
    out = []
    try:
        text = open(path, encoding="utf-8", errors="replace").read()
    except OSError:
        return []
    for raw in text.split("\n"):
        line = re.sub(r"(?<!#)#(?!#).*$", "", raw).replace("##", "#").strip()
        m = re.match(r"source\s*=\s*(.+)$", line)
        if m:
            src = expand_path(m.group(1).strip(), old_dir, os.path.dirname(path))
            for f in sorted(glob.glob(src)):
                out += hyprlang_lines(f, old_dir, seen)
            continue
        out.append(line)
    return out


def expand_path(p, old_dir, base):
    p = p.replace("$HOME", HOME)
    if p.startswith("~"):
        p = HOME + p[1:]
    hypr = os.path.join(HOME, ".config", "hypr")
    if p.startswith(hypr + "/"):            # the old folder may have been moved already
        p = os.path.join(old_dir, p[len(hypr) + 1:])
    if not os.path.isabs(p):
        p = os.path.join(base, p)
    return p


def parse_hyprlang(lines):
    """(monitors as dicts, autostart commands)"""
    variables, monitors, autostart = {}, [], []
    block, blockdepth = None, 0

    def subst(v):
        for k in sorted(variables, key=len, reverse=True):
            v = v.replace("$" + k, variables[k])
        return v

    for line in lines:
        if not line:
            continue
        if block is not None:               # inside monitorv2 { … }
            if line.startswith("}"):
                blockdepth -= 1
                if blockdepth == 0:
                    monitors.append(block)
                    block = None
                continue
            m = re.match(r"([\w.]+)\s*=\s*(.*)$", line)
            if m:
                block[m.group(1)] = subst(m.group(2).strip())
            continue
        if re.match(r"monitorv2\s*\{", line):
            block, blockdepth = {}, 1
            continue
        m = re.match(r"\$([\w-]+)\s*=\s*(.*)$", line)
        if m:
            variables[m.group(1)] = subst(m.group(2).strip())
            continue
        m = re.match(r"(monitor|exec-once|exec)\s*=\s*(.*)$", line)
        if not m:
            continue
        key, value = m.group(1), subst(m.group(2).strip())
        if key == "monitor":
            mon = monitor_from_hyprlang(value)
            if mon:
                monitors.append(mon)
        elif value:
            autostart.append(value)
    return monitors, autostart


def monitor_from_hyprlang(value):
    """monitor = name, mode, position, scale[, transform, N][, vrr, N]… → dict"""
    parts = [p.strip() for p in value.split(",")]
    if not parts:
        return None
    mon = {"output": parts[0]}
    if len(parts) >= 2 and parts[1] in ("disable", "disabled"):
        mon["disabled"] = "true"
        return mon
    if len(parts) >= 2 and parts[1].startswith("addreserved"):
        return None                     # reserved areas are not monitor layouts: dropped
    for key, i in (("mode", 1), ("position", 2), ("scale", 3)):
        if len(parts) > i and parts[i]:
            mon[key] = parts[i]
    rest = parts[4:]
    for i in range(0, len(rest) - 1, 2):
        mon[rest[i]] = rest[i + 1]
    return mon


# ---------------------------------------------------------------- Lua (hyprland.lua)

def lua_files(old_dir):
    files = []
    for root, _, names in os.walk(old_dir):
        files += [os.path.join(root, n) for n in sorted(names) if n.endswith(".lua")]
    return files


def strip_lua_comments(text):
    """Removes -- and --[[ ]] comments, leaving strings (which may contain --) alone."""
    out, i, n = [], 0, len(text)
    while i < n:
        c = text[i]
        if c in "\"'":
            j = i + 1
            while j < n and text[j] != c and text[j] != "\n":
                j += 2 if text[j] == "\\" else 1
            out.append(text[i:j + 1]); i = j + 1
        elif text.startswith("[[", i):
            j = text.find("]]", i + 2); j = n if j < 0 else j + 2
            out.append(text[i:j]); i = j
        elif text.startswith("--[[", i):
            j = text.find("]]", i + 4); i = n if j < 0 else j + 2
        elif text.startswith("--", i):
            j = text.find("\n", i); i = n if j < 0 else j
        else:
            out.append(c); i += 1
    return "".join(out)


def parse_lua(old_dir):
    monitors, autostart = [], []
    for f in lua_files(old_dir):
        try:
            text = open(f, encoding="utf-8", errors="replace").read()
        except OSError:
            continue
        text = strip_lua_comments(text)
        for m in re.finditer(r"hl\.monitor\s*\(\s*\{(.*?)\}\s*\)", text, re.S):
            mon = {}
            for kv in re.finditer(r"(\w+)\s*=\s*(\"[^\"]*\"|'[^']*'|[\w.\-]+)", m.group(1)):
                v = kv.group(2)
                mon[kv.group(1)] = v[1:-1] if v[0] in "\"'" else v
            if "output" in mon:
                monitors.append(mon)
        # hl.exec_cmd("…") calls (not hl.dsp.exec_cmd, which are keybinds)
        for m in re.finditer(r"(?<!dsp\.)\bhl\.exec_cmd\s*\(\s*(\"(?:[^\"\\]|\\.)*\"|'(?:[^'\\]|\\.)*'|\[\[.*?\]\])", text, re.S):
            s = m.group(1)
            s = s[2:-2] if s.startswith("[[") else s[1:-1].replace('\\"', '"').replace("\\'", "'").replace("\\\\", "\\")
            autostart.append(s)
    return monitors, autostart


# ---------------------------------------------------------------- running session

def session_monitors():
    if not os.environ.get("HYPRLAND_INSTANCE_SIGNATURE"):
        return []
    try:
        data = json.loads(subprocess.run(["hyprctl", "monitors", "all", "-j"], capture_output=True,
                                         text=True, timeout=5).stdout)
    except (OSError, ValueError, subprocess.SubprocessError):
        return []
    out = []
    for m in data:
        if m.get("disabled"):
            out.append({"output": m["name"], "disabled": "true"})
            continue
        mon = {
            "output": m["name"],
            "mode": "%dx%d@%.2f" % (m["width"], m["height"], m["refreshRate"]),
            "position": "%dx%d" % (m["x"], m["y"]),
            "scale": "%g" % round(m["scale"], 6),
            "transform": str(m.get("transform", 0)),
            "vrr": "1" if m.get("vrr") else "0",
            "bitdepth": "10" if "2101010" in (m.get("currentFormat") or "") else "8",
        }
        if m.get("mirrorOf") not in (None, "", "none"):
            mon["mirror"] = m["mirrorOf"]
        out.append(mon)
    return out


# ---------------------------------------------------------------- writing

NUMERIC = {"scale", "transform", "vrr", "bitdepth", "sdrbrightness", "sdrsaturation", "supports_wide_color",
           "supports_hdr", "sdr_min_luminance", "sdr_max_luminance", "min_luminance", "max_luminance",
           "max_avg_luminance"}
KNOWN = ["output", "disabled", "mode", "position", "scale", "transform", "mirror", "bitdepth", "vrr", "cm",
         "sdr_eotf", "icc", "sdrbrightness", "sdrsaturation", "supports_wide_color", "supports_hdr"]


def lua_value(key, v):
    v = str(v).strip()
    if key == "disabled":
        return "true" if v.lower() in ("1", "true", "yes", "on") else "false"
    if key in NUMERIC and re.fullmatch(r"-?\d+(\.\d+)?", v):
        return v
    return json.dumps(v)


def monitor_block(mon):
    keys = [k for k in KNOWN if k in mon]
    width = max(len(k) for k in keys)
    body = "".join("    %s = %s,\n" % (k.ljust(width), lua_value(k, mon[k])) for k in keys)
    return "hl.monitor({\n" + body + "})"


def write_monitors(path, monitors):
    blocks = [monitor_block(m) for m in monitors if m.get("output") is not None]
    if not any(m.get("output") == "" for m in monitors):
        blocks.append(FALLBACK)
    with open(path, "w", encoding="utf-8") as f:
        f.write(MONITORS_HEADER + "\n\n".join(blocks) + "\n")


def lua_string(s):
    if "]]" not in s and ("\"" in s or "\\" in s):
        return "[[" + s + "]]"
    return json.dumps(s, ensure_ascii=False)


def repo_autostart(conf):
    """Commands conf/autostart.lua already runs (not imported again)"""
    try:
        text = open(os.path.join(conf, "autostart.lua"), encoding="utf-8").read()
    except OSError:
        return set()
    return set(re.findall(r'hl\.exec_cmd\("((?:[^"\\]|\\.)*)"\)', text))


def write_autostart(path, commands, skip=()):
    seen, lines, commented = set(skip), [], 0
    for cmd in commands:
        cmd = cmd.strip()
        rules = ""
        m = re.match(r"^\[([^\]]*)\]\s*(.*)$", cmd)
        if m:                              # exec-once = [workspace 2 silent] app: the rules are dropped
            rules, cmd = m.group(1), m.group(2)
        if not cmd or cmd in seen:
            continue
        seen.add(cmd)
        why = next((reason for pat, reason in PROVIDED if re.search(pat, cmd)), None)
        note = "  -- had the rules [%s]" % rules if rules else ""
        if why:
            lines.append("    -- %s,  -- %s" % (lua_string(cmd), why))
            commented += 1
        else:
            lines.append("    %s,%s" % (lua_string(cmd), note))
    if not lines:
        return 0, 0
    with open(path, "w", encoding="utf-8") as f:
        f.write(AUTOSTART_HEADER + "\nreturn {\n" + "\n".join(lines) + "\n}\n")
    return len(lines) - commented, commented


def main(argv):
    old_dir = None
    if len(argv) >= 2 and argv[0] == "--from":
        old_dir, argv = argv[1], argv[2:]
    if len(argv) != 1:
        print(__doc__.strip().split("\n\n")[1], file=sys.stderr)
        return 2
    conf = argv[0]
    os.makedirs(conf, exist_ok=True)

    monitors, autostart = [], []
    if old_dir and os.path.isdir(old_dir):
        if os.path.isfile(os.path.join(old_dir, "hyprland.lua")):
            monitors, autostart = parse_lua(old_dir)
        else:
            monitors, autostart = parse_hyprlang(
                hyprlang_lines(os.path.join(old_dir, "hyprland.conf"), old_dir, set()))

    mpath = os.path.join(conf, "monitors.lua")
    if os.path.exists(mpath):
        print("monitors|kept|0")
    else:
        source = "config" if monitors else "session"
        if not monitors:
            monitors = session_monitors()
            if not monitors:
                source = "fallback"
        write_monitors(mpath, monitors)
        print("monitors|%s|%d" % (source, sum(1 for m in monitors if m.get("output"))))

    apath = os.path.join(conf, "autostart-local.lua")
    if not old_dir:
        print("autostart|skipped|0|0")
    elif os.path.exists(apath):
        print("autostart|kept|0|0")
    else:
        n, c = write_autostart(apath, autostart, repo_autostart(conf))
        print("autostart|%s|%d|%d" % ("written" if n + c else "none", n, c))
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
